### ISSUE TITLE
Unable to resolve host "www.google.com": No address associated with hostname

### ISSUE THREAD

**Issue by SCKC1** [cbeuw/GoQuiet-android#2] opened 2018-04-02 04:00 UTC
点击测试连接，等待很久，然后报错，
失败：Unable to resolve host "www.google.com": No address associated with hostname

![s80402-103027 -](https://user-images.githubusercontent.com/11403504/38182600-284cf832-366d-11e8-9c9f-ee3c1cce8bf2.jpg)

**Comment by kimw** [comment] 2018-04-02 04:11
1. Do your key/passphare has `=`, `;`, or `\` included? If it is, gq-android is not work in this release. Please wait for next one.

2. You can try turn off shadowsocks-android >> wait for 2-3 seconds >> trun on shadowsocks-android >> wait for 5-10 seconds >> then try to check connction. If this dose not work, wait for next release.

3. You may know that the GoQuiet-android is not stable as of now. The so called *RELEASE* is for tech review only.

**Comment by yhwfr1** [comment] 2018-04-02 08:05
目前可以正常联网了！

做了几件事：①~④
①、重启手机，
②、检查“后台启动”是否生效，
1.Do your key/passphare has =, ;, or \ included? If it is, gq-android is not work in this release. Please wait for next one.
③、改成相对简单的密码，重新输入
2.You can try turn off shadowsocks-android >> wait for 2-3 seconds >> trun on shadowsocks-android >> wait for 5-10 seconds >> then try to check connction.
④、按照指示操作一遍，中间出现过“Shakehand Error”提示，再打开就正常了

非常感谢~！

**Comment by hbxntsxw** [comment] 2018-04-02 11:29
@我按照你这么操作也成功了，谢谢！

**Comment by yhwfr1** [comment] 2018-06-03 04:06
很久没更新啦，更新一波吧~

**Comment by chenshaoju** [comment] 2018-09-07 04:16
This issue is pretty annoying. Sometimes need least 10 times to retry.

In my case, No necessity to restart shadowsocks or phone, Just disconnect in Shadowsocks, And wait 5 seconds and reconnect, After connected, Wait 5 seconds to test connectivity, If failed, just retry again.

But it's still can be working, Thank you for developing this plugin. :+1:

**Comment by cbeuw** [comment] 2018-09-07 17:54
@chenshaoju 
Sorry I've been quite lazy over the last few months. I didn't touch on this project at all and I almost forgot the existence of this bug. I just started working on it again. Don't have any clue yet but hopefully I'll be able to deliver a solution soon.

**Comment by cbeuw** [comment] 2018-09-09 15:26
This issue is weird. The app works perfectly fine on the emulator but not on metal. Maybe it's caused by the difference between x86 and arm? But the plugin works fine on arm-based Raspberry Pi. 

I do see a pattern, however. Whenever the remote closes a connection first (which then triggers gq-client to close the ss connection on the same pipe), the thing won't work. However if it's ss that closes the connection first, the thing would run. I tried to make the client to never initiate the closing of an ss connection, the problem still persists.

**Comment by cbeuw** [comment] 2018-09-16 22:45
@madeye @mygod
Did you encounter this problem (pressing connect doesn't always work) in kcptun or simple-obfs?

**Comment by madeye** [comment] 2018-09-17 02:38
@cbeuw Nope, I didn't this issue.

BTW, we're now using go1.11 APIs to protect the socket, you may want to have a try. https://github.com/shadowsocks/overture/blob/4ea07479b42eef0e47d29cfa9559e37f995f0a58/core/utils/utils_android.go

**Comment by cbeuw** [comment] 2018-09-17 21:57
@madeye 
Thanks for the reply! I will look into this new API.

**Comment by cbeuw** [comment] 2018-09-18 15:51
Yup it works when I use the vanilla net package from go1.11 instead of gotfo.

I decided to drop TCP Fast Open support. Before go1.11 gotfo was useful not only for TCP Fast Open, but also the fact that I don't have to compile the go compiler myself for the callback protector to work (not that it worked well). Now gotfo is just a burden. Its dirty hack is unmaintainable anyway and we'll wait for future go versions for the TCP Fast Open support.

**Closed** 2018-09-18 22:49 UTC

**Comment by chenshaoju** [comment] 2018-09-20 02:27
After a few times test, The v1.0.0 has fixed this issue.
Thank you!

**Comment by jutdoit** [comment] 2018-10-27 07:28
我的这个ssr用手机客户端连接能用，用电脑客户端却不能用，这是什么问题？？

**Comment by chenshaoju** [comment] 2018-10-27 07:46
你需要使用SSR的PC客户端才行，SS+GoQuite不能兼容SSR的混淆。

**Comment by narutojxl** [comment] 2019-03-22 16:04
same problem, not solved by what  @SCKC1  did, any idea?

**Comment by chenshaoju** [comment] 2019-03-23 03:08
Please check your Shadowsocks client configure is correct.
Maybe case by wrong server IP, port, method, and password. Make sure is the same with the server.

**Comment by timothy2005** [comment] 2019-10-10 02:27
Reason:
GCP(Google Cloud Platform) only open 2 ports by default: **80** and **443**
If you use **any other ports**, you need allow it in **Firewall** setting, otherwise, you will get this error.

If you don`t know how to set firewall rule, the best way for you is: **using 443 as the port number**

**Comment by JackFe** [comment] 2020-03-13 05:29
1、4.6.1升级至5.0.5
2、进入Shadowsocks应用详情：①设置为自启动；②省电策略设置为无限制
3、重启手机，恢复正常

**Comment by vyckey** [comment] 2023-03-17 11:58
it doesn't work, anyone knows how to resolve it?
